name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install coveralls

      - name: Run tests with coverage
        run: |
          coverage run -m pytest tests/
          coverage report

      - name: Upload to Coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS }}
	    DB_URL: ${{ secrets.DB_URL }}
    	    SYNC_DB_URL: ${{ secrets.SYNC_DB_URL }}
  	    REDIS_HOST: ${{ secrets.REDIS_HOST }}
  	    REDIS_PORT: ${{ secrets.REDIS_PORT }}
            REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
  	    BASE_DIR: ${{ secrets.BASE_DIR }}
        run: coveralls
